name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform workspace select dev
      - run: terraform apply -auto-approve